### ISSUE TITLE
[nice to have] -  add icons to our charts

### ISSUE THREAD

**Issue by springdo** [redhat-cop/helm-charts#102]
OpenShift 4.6 includes the ability to add helm repos as catalogs in the dev view. We should add icons to the helm charts so they look nice in OCP Land and don't just have the generic Helm Logo.

<img width="1316" alt="helm-integration" src="https://user-images.githubusercontent.com/6122439/98238375-34505980-1f5e-11eb-8767-8945d6775b2c.png">

FYI - @ckavili / @mvmaestri

**Comment by ckavili** [comment]
`provided by Ubi Journey` too lazy to write the full name 🙈
