### ISSUE TITLE
Ploigos gets stuck on cluster-check

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/helm-charts#135]
I've just tried to install ploigos, but it gets stuck on the cluster-check (CRD never gets created)

```
cd ploigos
export project_name="ploigos-$(date +'%d%m%Y')"
oc new-project ${project_name}
helm install ploigos -f values.yaml --set-string operator.namespaces[0].name=${project_name} .
```

@eformat ; any ideas?

**Comment by eformat** [comment]
yup .. looks like older operator versions not in catalog anymore ... updating

https://github.com/redhat-cop/helm-charts/pull/136
