### ISSUE TITLE
template vs install vs argocd

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/helm-charts#138]
what is the expectation from this repo around $subject? i.e.: do we expect all charts can be installed by `helm template` and run on `argocd`?

I presume that's not 100% true, as I know some charts use hooks that template/argo don't support.

Q: do we expect all charts should run on argo without issue?
Q: should we standardise in a certain way? template vs install
Q: or do we just need to call out in the readme's what is supported/not?

thoughts @ckavili @springdo @eformat

**Comment by eformat** [comment]
Can we close this @garethahealy  ? the short answer is no, you can use helm lifecycle events in your charts.

We have charts that have lifecycle hooks etc. They still work in ArgoCD - i have used values/flags e.g. "ignoreHelmHooks" in some charts so the bits that are involved do not deploy in ArgoCD.

Other useful things to do in your chart, for example if you have to wait for a Subscription to add a CRD in ArgoCD - is to add this annotation
```
argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
```
