### ISSUE TITLE
argocd testing

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/helm-charts#139]
i pushed the prow.sh, which can be used locally but is hoped would be used by prow CI in the future (TBD). but do we need another test scenario to check the charts work in argocd?
- https://github.com/redhat-cop/helm-charts/blob/master/_test/prow.sh

i.e.: a script that creates all the charts in an argocd instance and checks they've all run successfully.

thoughts @ckavili @springdo @eformat ?

**Comment by ckavili** [comment]
it'd be nice to check if post hooks are working as expected after sync, etc. I actually would like to have this for UJ apps with defined override values in that repo (for external charts as well😁)

**Comment by garethahealy** [comment]
stale, dont think this is going to go anywhere.
