### ISSUE TITLE
run release on pr

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/helm-charts#147]
is there an approach we can take to run the release workflow on PR? I am thinking about where PRs are raised which change this workflow. there isn't anything in the PR to say it works or not, it's down to the reviewer to check the workflow on the PR raisers repo (i.e.: upstream)

wondering if we could do a draft release? or the version based on the PR number? i.e.: {chart}-PR{pr-number}

thoughts? @ckavili @springdo @eformat @tylerauerbeck

**Comment by garethahealy** [comment]
reading docs, dont think its possible using the helm action:
- https://github.com/helm/chart-releaser

unless we had a different github repo to push releases to... but even then we'd need to handle multiple releases from 1 PR

**Comment by tylerauerbeck** [comment]
This may be a bit overkill. But the action does provide the ability to specify what branch to publish to. We could have this PR workflow dynamically create the branch, have the chart releaser push to that branch and then do whatever validation we need against that branch (and then whatever cleanup needs to happen once validation is complete).

**Comment by garethahealy** [comment]
@tylerauerbeck ; reason this came about is because the release is failing on master:
- https://github.com/redhat-cop/helm-charts/actions/workflows/release.yaml

not sure if its a flake or something real (error message doesn't tell us which chart is wrong) but if the action was triggered on PR, we'd not hit this.

**Comment by garethahealy** [comment]
https://github.com/helm/chart-releaser/pull/119

**Comment by garethahealy** [comment]
re: releasing to a branch. cant see where that's mentioned:
- https://github.com/helm/chart-releaser#create-github-releases-from-helm-chart-packages
- https://github.com/helm/chart-releaser-action#inputs

got a link?

**Comment by garethahealy** [comment]
closing as it's not possible/a simple thing to do
