### ISSUE TITLE
s/master/main/g 🥢

### ISSUE THREAD

**Issue by ckavili** [redhat-cop/helm-charts#186]

**Comment by garethahealy** [comment]
@ckavili ; want me to rename the default branch?
<img width="795" alt="Screenshot 2022-01-19 at 08 37 39" src="https://user-images.githubusercontent.com/8656974/150094079-1df3531e-1db1-4bf0-bf1f-2113c680e2e8.png">

**Comment by ckavili** [comment]
yeah I was planning to do that and now I can't remember why I didn't do it 🤦  since our other repos use `main` as the default branch, we can rename this one too. We just need to updates source refs on UJ side  - like this one: https://github.com/rht-labs/ubiquitous-journey/blob/main/ubiquitous-journey/values-tooling.yaml#L180
