### ISSUE TITLE
ClusterServiceVersion is not deleted after helm uninstall action

### ISSUE THREAD

**Issue by mabulgu** [redhat-cop/helm-charts#19]
After creating a operator subscription with the helm operatorhub chart, it creates the subs successfully:

For example lets install the amq-streams operator with the operatorhub chart:

`helm install rht-labs/operatorhub --generate-name --set operators[0].name=amq-streams,operators[0].namespace=rht-labs-trials,operators[0].subscription.operatorName=amq-streams,operators[0].subscription.channel=stable,operators[0].subscription.csv=amqstreams.v1.4.0,operators[0].operatorgroup.create=true`

It creates the helm instance successfully: 

NAME: operatorhub-0-1586213116
LAST DEPLOYED: Tue Apr  7 01:45:18 2020
NAMESPACE: rht-labs-trials
STATUS: deployed
REVISION: 1
TEST SUITE: None

And installs the operator:

<img width="1344" alt="Screen Shot 2020-04-07 at 01 55 52" src="https://user-images.githubusercontent.com/10568159/78612879-13fad800-7873-11ea-9eb4-71bdd1499188.png">

But when trying to uninstall the chart, it does remove the resources that are created by itself but not the ClusterServiceVersion which is created automatically while subscribing:

<img width="1341" alt="Screen Shot 2020-04-07 at 00 50 52" src="https://user-images.githubusercontent.com/10568159/78612972-4a385780-7873-11ea-9d31-015d21c46df4.png">

<img width="1005" alt="Screen Shot 2020-04-07 at 00 51 09" src="https://user-images.githubusercontent.com/10568159/78612979-515f6580-7873-11ea-98d9-522c77548818.png">

**Comment by eformat** [comment]
hi @mabulgu - i wonder if this is fixing the right thing ? the CSV is automatically created by the OLM from the catalog source. So when you create a subscription and operatorgroup, the OLM queries the CatalogSource to create the CSV

im wondering - if you manually delete the operator using the OLM (UI) does it remove the CSV correctly ?

**Comment by mabulgu** [comment]
Hi Mike (@eformat),

Actually I don't do a "oc delete -f -", I run the "helm uninstall" command. The behavior I expect when I run "helm uninstall" for the installed helm is to uninstall all the operator resources.

https://yadi.sk/i/BexsDtuMO_eCcw

The native behavior of the operator when I delete it manually is: there is only one resource left which is the OperatorGroup. It is also deleted when "helm uninstall" used but its being deleted is not a problem since helm should work this way: it should delete the resources it created: operatorgroup, subscription:

https://yadi.sk/i/ISfahA38YvuIYA

With the fix #20, a post-delete action is triggered on the related ClusterServiceVersion after "helm uninstall" which deletes all the operator relevant resources that is created/triggered to be created by helm chart:

https://yadi.sk/i/R1IPN559PqTepw

**Comment by ckavili** [comment]
hey Aykut! 👋 soooo I've been doing some spring cleaning.. 😅 since CSV is not removed with `helm uninstall..` due to not having helm annotations and having a simple csv template doesn't work with `helm template ... | oc apply -f- ` , how about having a `pre-delete helm hook` to remove currentCSV which would run before uninstalling og and subs? something like this:

```
{{- if .Values.operators }}
{{- range $op := .Values.operators }}
{{- $sub := $op.subscription }}
---
apiVersion: v1
kind: Pod
metadata:
  name: delete-csv-post-hook
  annotations:
    "helm.sh/hook": pre-delete
    "argocd.argoproj.io/hook": skip
spec:
  containers:
    - image: quay.io/openshift/origin-cli:latest
      command:
        - /bin/bash
        - -c
        - |
           csv=` oc get subs {{ $op.name }}  -o yaml |  grep "  currentCSV:" |cut -d':' -f2`
           oc delete csv $csv -n {{ $op.namespace }}
      imagePullPolicy: IfNotPresent
      name: delete-csv-post-hook
  serviceAccount: csv-serviceaccount
  serviceAccountName: csv-serviceaccount
{{- end }}
{{- end }}
```

Since Argo cd runs `helm template...`, and can cleanup CSVs upon Application deletion, we don't need to sync this object. And `"argocd.argoproj.io/hook": skip` can help us there (plus, ArgoCD doesn't support helm pre-delete hook 🤷 )

what do you think @mabulgu @eformat? 😕

**Comment by mabulgu** [comment]
Hi Cansu. TBH rather than putting a resource that makes some changes on other resources I would prefer sth that does not create a CSV but delete it with a post-delete action as I proposed in the PR I created for this issue:

https://github.com/redhat-cop/helm-charts/pull/20/files#diff-30b6317e7fe9bd33b4870cee33cc89f6e979292b9e14b23c1fd9cbcfe5d50f59

   ```{{- if .Values.operators }}
{{- range $op := .Values.operators }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: {{ $op.subscription.csv | quote }} 
  namespace: {{ $op.namespace | quote }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}
{{- end }}```

This seems less complex but of course, we have to test it against ArgoCD maybe `"argocd.argoproj.io/hook": skip` should be added here as well.

This CR of CSV does not create a resource but deletes it IIRC right after the uninstall. This should also work with `helm template ... | oc delete -f-`. I can re-open a PR if you like.

**Comment by ckavili** [comment]
that was quick! :) so this makes sense too 🙈 let me try with Argo cd skip hook and put some thought on it because this only removes the initial CSV (with throwing an error) and with automatic updates, there might be additional CSVs that we might want to remove 🤔 (promise, won't take almost a year to reply this time :D )

@eformat would love your input here as well! thanks :)

**Comment by mabulgu** [comment]
> it because this only removes the initial CSV (with throwing an error) 

The one I shared throws an error? I dont really remember but I have to check the videos that I shared for this issue/PR as a solution.

**Comment by ckavili** [comment]
yeah it's because there is no spec in csv template but it does the deletion 🙃

```
Error: uninstallation completed with 1 error(s): unable to build kubernetes object for post-delete hook operatorhub/templates/csv.yaml: error validating "": error validating data: ValidationError(ClusterServiceVersion): missing required field "spec" in com.coreos.operators.v1alpha1.ClusterServiceVersion
```

**Comment by mabulgu** [comment]
Hi, @ckavili! Check out the last video(https://yadi.sk/i/R1IPN559PqTepw) here pls (I just rechecked in order to remember):

https://github.com/redhat-cop/helm-charts/issues/19#issuecomment-610273697

This seems to be fixing the uninstall issue without any errors returning. But pls do test this with the ArgoCD as well if you have one up and running somewhere (I don't have a running argocd right now).

If this works I can happily re-create my PR for this.

**Comment by mabulgu** [comment]
> yeah it's because there is no spec in csv template but it does the deletion 🙃
> 
> ```
> Error: uninstallation completed with 1 error(s): unable to build kubernetes object for post-delete hook operatorhub/templates/csv.yaml: error validating "": error validating data: ValidationError(ClusterServiceVersion): missing required field "spec" in com.coreos.operators.v1alpha1.ClusterServiceVersion
> ```

Ah sorry just saw this. Is this error from ArgoCD? Because I don't have a error when I run `helm uninstall`. If so can you try it out with a skip just like you did for your solution?

**Comment by mabulgu** [comment]
In the meanwhile pls let me check the `missing required field "spec" in com.coreos.operators.v1alpha1.ClusterServiceVersion` in a new ocp cluster because it's been quite a long time since I created this issue

**Comment by eformat** [comment]
@mabulgu, @ckavili  - can we close this ?

non deleting CSV's is really a finalizer issue on the relevant Operator. And we should not be explicitly deleting them here i think.

**Comment by mabulgu** [comment]
> @mabulgu, @ckavili  - can we close this ?
> 
> non deleting CSV's is really a finalizer issue on the relevant Operator. And we should not be explicitly deleting them here i think. 

Go ahead pls. I can checkout again and create another issue/pr for this if I needed. Thanks!

**Comment by eformat** [comment]
thank @mabulgu !
