### ISSUE TITLE
ArgoCD HA Redis SA has too wide permissions.

### ISSUE THREAD

**Issue by jtudelag** [redhat-cop/helm-charts#190]
I believe this does not need to be a ClusterRole, plus the SA is named: *argocd-argocd-reids-ha*.

https://github.com/redhat-cop/helm-charts/blob/b0083772e02a12c815f8d0ff7344db871375308c/charts/argocd-operator/templates/anyuid-scc.yaml#L18

**Comment by jtudelag** [comment]
Fixing it here: https://github.com/redhat-cop/helm-charts/pull/191/files

**Comment by springdo** [comment]
closing as you've merged changes already
