### ISSUE TITLE
Charts using the removed APIs in k8s 1.22 requires changes🧩

### ISSUE THREAD

**Issue by ckavili** [redhat-cop/helm-charts#202]
[Deprecated APIs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) `extensions/v1beta1` and `networking.k8s.io/v1beta1` needs to be migrated to ` networking.k8s.io/v1` in below charts.

- [sonarqube chart](https://github.com/redhat-cop/helm-charts/tree/master/charts/sonarqube)
- [etherpad chart](https://github.com/redhat-cop/helm-charts/tree/master/charts/etherpad)
- [nexus chart](https://github.com/redhat-cop/helm-charts/tree/master/charts/sonatype-nexus)

**Comment by garethahealy** [comment]
fyi: the gh-action (validate) should cover this, but the latest checks aren't covered yet
- https://github.com/redhat-cop/rego-policies/issues/171

**Comment by eformat** [comment]
@ckavili - updated these, linked (and took oppty to also upgrade minor versions where applicable)
