### ISSUE TITLE
Unable to access to ArgoCD UI in Firefox: SEC_ERROR_BAD_DER

### ISSUE THREAD

**Issue by rmarting** [redhat-cop/helm-charts#209]
Deploying ArgoCD following the instructions in [README.md](https://github.com/redhat-cop/helm-charts/blob/master/charts/argocd-operator/README.md) with default values works smothly, however it is not possible to access to the UI using Firefox.

The following messages are showed in the browser without any capability to navigate:

```text
Secure Connection Failed

An error occurred during a connection to argocd-server-labs-ci-cd.apps.cluster-e381.e381.sandbox1862.opentlc.com. security library: improperly formatted DER-encoded message.

Error code: SEC_ERROR_BAD_DER

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

The same route works successfully in Chrome.

Environment:
* OpenShift 4.8
* ArgoCD Operator 0.0.15
* Firefox 94.0 (64-bit)
* Fedora 34

PS: Open this issue initialy here, as I am not sure if the issue is related with the Helm Chart, OpenShift 4.8 (provided by RHPDS) or finally it is an issue of Argo CD.

**Comment by eformat** [comment]
hi @rmarting  this is likely related to Firefox and self signed certs.

can you try:

1. about:config
2. switch network.stricttransportsecurity.preloadlist -> false
3. restart browser

I just tried with FF93, FC34 on a *.dev domain (HTST) - worked OK for me.

![Screenshot from 2021-11-17 07-26-50](https://user-images.githubusercontent.com/712608/142068650-e93da1dd-0a52-4fb5-a7a8-2b7d3095e242.png)

Also note that once the argocd operator v0.1.0 releases into the community via OLM, we can make use of this new feature:  

# feat: Enable service CA for reencrypt routes to argocd-server on OpenShift
https://github.com/argoproj-labs/argocd-operator/pull/326

**Comment by rmarting** [comment]
@eformat It is not working in my environment (FF94, Fedora34), adding the following properties in my FF configuration (`about:config`):

```text
security.tls.insecure_fallback_hosts = <argocd-dashboard-host>
network.stricttransportsecurity.preloadlist = false
```

So, it is related with FF. Maybe we could maintain this issue open to confirm and verify the new feature before to close it. Does it suit for you?

**Comment by eformat** [comment]
hi @rmarting i am going to close this for now. Firefox94.

![Screenshot from 2021-11-26 08-35-25](https://user-images.githubusercontent.com/712608/143505133-b9f76786-872b-4dba-bddf-dc6951fd8feb.png)

One thing to note - i have recently pushed #211 - the GitOps operator on OpenShift now supports reencrypt Routes which will get around client browser config issues with real certs.
