### ISSUE TITLE
Plugins.txt

### ISSUE THREAD

**Issue by bigfoot6uk** [redhat-cop/helm-charts#212]
Hi, 

Is there a way that I can add a plugins.txt file with a team needed plugins somewhere?

**Comment by ckavili** [comment]
hey @bigfoot6uk do you mean Jenkins plugins?

**Comment by bigfoot6uk** [comment]
Hey, yes  jenkins plugins

**Comment by eformat** [comment]
hi @bigfoot6uk - in the chart - the jenkins container image build is driven from this s2i git repository:

buildconfigs.source_repo = https://github.com/rht-labs/s2i-config-jenkins

that has a plugins.txt in it. you could fork this for your own uses to customize it. that is probably the quickest way.
the chart does not expose the plugins.txt for overriding explicitly.

If you dont want to make it part of the build, use INSTALL_PLUGINS env var on the deployment config - this works as well. See https://github.com/openshift/jenkins.

**Comment by bigfoot6uk** [comment]
@eformat Thanks so much for your response.

**Comment by eformat** [comment]
no problem, i will close this for now.
