### ISSUE TITLE
How to deploy gitops operator on a different namespace instead of labs-ci-cd

### ISSUE THREAD

**Issue by sathe06** [redhat-cop/helm-charts#359]
We were trying to deploy gitops operator using helm chart using terraform's helm_release
by default its using labs-ci-cd as a namespace.

The requirement was to deploy this on another namespace instead of labs-ci-cd

can someone help us on this

@garethahealy  @ckavili 
Sorry. Not sure whom to ask so creating a issue here.

**Comment by sathe06** [comment]
Thanks @garethahealy 

Can you please share the version link for RH-gitops-operator.
i mean list of released version so that it will be useful from migration perceptive

**Comment by garethahealy** [comment]
- https://github.com/redhat-cop/helm-charts/releases

**Comment by sathe06** [comment]
@garethahealy 
Final doubt, by default this operator getting installed/configured on all namespaces.

while removing operator from its namespace its successfully removed, But still operator available on other namespaces

**Comment by eformat** [comment]
operator is installed at global scope (preferred). the operands (ArgoCD) are not removed when removing the operator. this is normal behavior for the operator pattern.

**Comment by sathe06** [comment]
@garethahealy @eformat 

If we want to install Red Hat OpenShift GitOps-1.6.0
ref: https://docs.openshift.com/container-platform/4.10/cicd/gitops/gitops-release-notes.html

can you please share  below details for this
appVersion: 
version:

**Comment by garethahealy** [comment]
have you tried setting the version?
- https://github.com/redhat-cop/helm-charts/blob/master/charts/gitops-operator/templates/subscription.yaml#L15

**Comment by sathe06** [comment]
@garethahealy  
Yes, i have tried that. Its not installing correct version

operator:
  version: 1.6.0

![image](https://github.com/redhat-cop/helm-charts/assets/64068637/4e0f6394-5d82-46a3-a821-bb6765e1183b)

**Comment by ckavili** [comment]
hey @sathe06 you shouldn't worry about Helm Chart version or the appVersion in the Chart.yaml as those variables are not being used within the chart templates. The helm chart installs the latest available OpenShit GitOps operator available for your cluster but if you'd like to deploy a specific version, you need to change this [value](https://github.com/redhat-cop/helm-charts/blob/master/charts/gitops-operator/values.yaml#L14). as @garethahealy shared. I'd say leave it as it is..and GitOps operator version and Argo CD version are two different things so you can also manage Argo CD instance version from this [value](https://github.com/redhat-cop/helm-charts/blob/master/charts/gitops-operator/values.yaml#L35) If you don't want to specify the version or don't know which one to use, you can leave that our and Operator will deploy the available one for you:)

**Comment by sathe06** [comment]
Thank you all, closing this one
