### ISSUE TITLE
Cant deploy sonarqube.

### ISSUE THREAD

**Issue by jtudelag** [redhat-cop/helm-charts#61]
It seems the sonarqube deployment and the postgresql dc are using the same Claim volume name.... and also that there isnt a PVC for postgresql...

**Comment by jtudelag** [comment]
We need a CI: https://github.com/rht-labs/helm-charts/issues/61

**Comment by ckavili** [comment]
Sonarqube seems fine now :) for CI, we have https://github.com/redhat-cop/helm-charts/issues/15 and things in my mind hoping to discuss with you soon 😇
