### ISSUE TITLE
Switch CR_TOKEN to the ci bot

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/helm-charts#87]
Currently, CR_TOKEN is @springdo - probably a good idea to switch it to @redhat-cop-ci-bot

**Comment by springdo** [comment]
yo - yeah happy to move this if someone gives me a token. When I moved the library from `rht-labs` myself and @sabre1041 just used my token to ensure things would continue work with releasing etc

**Comment by garethahealy** [comment]
@pabrahamsson ; can you generate a token from the bot and replace CR_TOKEN with it in the settings?

**Comment by tylerauerbeck** [comment]
@garethahealy I actually don't think the bot actually needs super special permissions anymore. From a few other working examples, I see that `${{ secrets.GITHUB_TOKEN }}` has enough juice to do the necessary commits.

**Comment by springdo** [comment]
I think this is done right? Im not getting Donal released a new version type messages anymore.
