### ISSUE TITLE
sonar.properties not being reflected

### ISSUE THREAD

**Issue by mkm29** [redhat-cop/helm-charts#92]
The chart correctly initializes the container (downloads and installs plugins and populated the conf/sonar.properties file, however, the properties set are not being reflected. Is there a command that I need to run to make the changes stick?

I tested this with SMTP settings and the server did not pick them up. These are core settings in SQ, and there are a lot of settings that I need to set for plugins such as the OpenShift authentication plugin.

**Comment by ckavili** [comment]
hey Mitch. Thanks for reaching out! did you check that if properties are populated in `sonarqube-config` configmap? I just tested with the following override values and can see the proxy values in Administrator > System settings.

```
sonarProperties:
  http.proxyHost: proxy.cansu.com
  http.proxyPort: 8080
```

**Comment by mkm29** [comment]
Hi, thanks for the response! Ya, I did check the config map, and used http.proxy as a test. That configuration setting was reflected in Administration > System > Web, however any setting that I need to update (Administration > General) were not reflected. Here are a few of the settings that I need to set:

email.from=noreply@agilesof.com
email.fromName=Agile Dagger
email.smtp_host.secured=HOST
email.smtp_password.secured=PASSWORD
email.smtp_secure_connection.secured=ssl
email.smtp_username.secured=USERNAME
sonar.es.bootstrap.checks.disable=true

**Comment by ckavili** [comment]
Actually, you can see the values are set if you try to send a test email from Administration > General tab. (Cause I got an error `HOST. Couldn't connect to host, port: HOST, 25; timeout 30000. Sending the email to the following server failed : HOST:25` error) It just doesn't show in UI, don't know why..Can you test an email to see if it works out for you?

**Comment by mkm29** [comment]
Oh wow it actually is setting the properties they just don't show up on the web UI...thanks! I wonder if there is a way to force the web UI to update?

**Comment by ckavili** [comment]
Not that I know of, sorry.
